/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swangq_com_suanfa_BreakpadActivity */

#ifndef _Included_com_swangq_com_suanfa_BreakpadActivity
#define _Included_com_swangq_com_suanfa_BreakpadActivity
#ifdef __cplusplus
extern "C" {

JNIEXPORT void JNICALL Java_com_swangq_com_suanfa_BreakpadActivity_crash
  (JNIEnv *, jobject);
}
